name: Ruff
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff-lint:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with Ruff
        run: ruff check --ignore=E722 --output-format=github .
        continue-on-error: false

